### 변수 정의

In [1]:
a = 1 ; b = 2
print(a)
print(b)

1
2


In [3]:
a

1

In [4]:
b

2

In [5]:
a
b

2

In [6]:
type(a)   #int: integer 정수

int

In [7]:
a = 1.0

In [8]:
type(a)   #float: 소수

float

In [9]:
int(a)  #type을 정수로 바꿔준다.

1

In [10]:
a = 1.1

In [11]:
int(a)

1

In [12]:
float(int(a))

1.0

In [13]:
a = 1; a = float(a); print(type(a))

<class 'float'>


## String

In [14]:
a = '123' #'123'은 숫자가 아니라 문자

In [15]:
a

'123'

In [16]:
type(a)

str

In [17]:
a = 'abc'

In [18]:
a[1]

'b'

In [19]:
a[0] #python은 첫번째가 1이 아니라 0

'a'

In [20]:
a[2]

'c'

In [21]:
a[-1]  #0은 첫번째, -1은 마지막!!

'c'

In [22]:
a[-2]

'b'

##### list 대괄호와 콤마(,)로 구분된다

In [23]:
a = [1, 2, 3] #숫자 1,2,3이 나열된 것

In [24]:
a

[1, 2, 3]

In [25]:
type(a)

list

In [26]:
a = [1, 2, 'ab', [4, 5]]

In [27]:
type(a)

list

In [28]:
a[0]

1

In [29]:
a[-1]

[4, 5]

In [30]:
a[-1][0]

4

In [31]:
a = 'abc'; a = list(a)

In [32]:
a

['a', 'b', 'c']

In [1]:
a = (1, '2', [3, '4']); print(type(a)); print(a[0]); print(a[-1][-1])

<class 'tuple'>
1
4


#### variable dictionary, have to use { }

In [33]:
a = {"a": "apple", "b": "orange", "c": 2014}
print(type(a))
print(a["a"])

<class 'dict'>
apple


In [34]:
a["c"]

2014

### numpy

In [2]:
a = [(1,2,3), (3,8,0)]
print(type(a))
a

<class 'list'>


[(1, 2, 3), (3, 8, 0)]

In [3]:
import numpy as np #import : 하드디스크에 다운받고 메모리에 올리는 것. numpy는 기본으로 들어있지 않아서 import를 통해 메모리에 가져와야 한다.
                   #as np 안쓰면 b=numpy.array(a)이렇게 써줘야 함. as np하면 b=np.array(a)
b = np.array(a)
print(b)
print(type(b)) #array: 행렬이 없는 파이썬에서 행렬을 처리하는 방식

[[1 2 3]
 [3 8 0]]
<class 'numpy.ndarray'>


In [4]:
print(b*b) #진짜 행렬에서는 2X3행렬과 2X3행렬을 곱할 수 없는데, array는 진짜 행렬은 아니라서 곱할 수 있다.

[[ 1  4  9]
 [ 9 64  0]]


In [5]:
c = np.matrix(b)
print(c)
print(type(c))

[[1 2 3]
 [3 8 0]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [6]:
print(c*c)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
c*c.T #transpose 해주면 이제 곱할 수 있다.

matrix([[14, 19],
        [19, 73]])

In [2]:
a = [1, 2, 3, 4]
for i in a: #첫번쨰 루프에서는 1, 두번째에서는 2, ,,, a 다음에 : 꼭필요
    print(i) #tab 필요. tab안하면 end써줘야한다

1
2
3
4


In [3]:
len(a)  #len(a)는 개수

4

In [4]:
range(4)

range(0, 4)

In [5]:
a = [1, 2, 3, 4]
for i in range(len(a)):
    print(i)

0
1
2
3


In [6]:
a = [1, 2, 3, 4]
for i in range(4):
    print(a[i])

1
2
3
4


In [8]:
a = ["red", "green", "blue", "purple"]
b = [0.2, 0.3, 0.1, 0.4]
for i, a in enumerate(a):  #index와 i를 동시에 가져가는 것, 첫번째 루프는 i 0, a red
    print("{}: {}%".format(a, b[i]*100))

red: 20.0%
green: 30.0%
blue: 10.0%
purple: 40.0%


In [9]:
a = ["red", "green", "blue", "purple"]
b = [0.2, 0.3, 0.1, 0.4]
for a_, b_ in zip(a, b):
    print("{}: {}%".format(a_, b_*100))

red: 20.0%
green: 30.0%
blue: 10.0%
purple: 40.0%


In [10]:
a = 0
if a == 0: #변수 assign할 때는 =, 수학적 등호일 때는 ==, for 루프와 마찬가지로 : 꼭 해주기
    print(a)
else:       #a가 0이 아니면
    print(a+1)

0


In [11]:
for i in range(1, 3): #range(1, 3) = 1, 2
    for j in range(3, 5):
        print(i*j)

3
4
6
8


In [12]:
for i in range(1, 3):
    for j in range(3, 5):
        if j >=4:
            print(i*j)

4
8


In [14]:
a = [1, 2, 3, 4]
b = [i for i in a if i >=2] #for 루프가 list 안에 들어가 있다.
b

[2, 3, 4]

In [15]:
a = ['red', 'green', 'blue', 'purple']
b = [i for i in a if len(i) >=4]  #len('red'는 글자수, 즉 3, len(i) >=4라는 것은 글자수가 4 이상인것을 의미
b

['green', 'blue', 'purple']